<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
    <style>

.dropbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
  cursor: pointer;
}


.dropdown {
  position: relative;
  display: inline-block;
}


.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}


.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {background-color: #f1f1f1}

.dropdown:hover .dropdown-content {
  display: block;
}

.dropdown:hover .dropbtn {
  background-color: #3e8e41;
}
</style>
</head>
<body>
<div class="dropdown">
    <button class="dropbtn">Versiones</button>
    <div class="dropdown-content">
    <a href="#">10.0.0.1 | 10 de noviembre de 2018 </a>
    <a href="#">10.0.0.3 | 11 de noviembre de 2019 </a>
    <a href="#">10.0.0.7 | 12 de noviembre de 2020 </a>
</div>
    <textarea name="write here" id="yo" cols="50" rows="30">Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur poss</textarea>
    <input type="submit" name="save">
</div>
</body>
</html>